window.sr=ScrollReveal();
sr.reveal('.showcase-top',{
    duration:3000,
    origin:'top',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.card-left',{
    duration:3000,
    origin:'left',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.card-bottom',{
    duration:3000,
    origin:'bottom',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.card-right',{
    duration:3000,
    origin:'right',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.column-left',{
    duration:3000,
    origin:'left',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.column-right',{
    duration:3000,
    origin:'right',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.column-top',{
    duration:3000,
    origin:'top',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('.column-bottom',{
    duration:3000,
    origin:'bottom',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal(' #connect .connect-text',{
    duration:4000,
    origin:'top',
    distance:'150px',
    viewFactor:0.3
  })
  sr.reveal('  #connect .connect-logo',{
    duration:4000,
    origin:'bottom',
    distance:'150px',
    viewFactor:0.3
  }) 
  sr.reveal('.writeus',{
    duration:4000,
    origin:'top',
    distance:'150px',
    viewFactor:0.3
  }) 
  sr.reveal('.writeform',{
    duration:4000,
    origin:'bottom',
    distance:'150px',
    viewFactor:0.3
  }) 
  sr.reveal('.galleryheading',{
    duration:4000,
    origin:'left',
    distance:'150px',
    viewFactor:0.3
  })  
  sr.reveal('.imggallery',{
    duration:4000,
    origin:'right',
    distance:'150px',
    viewFactor:0.3
  }) 